### ISSUE TITLE
Electrode

### ISSUE THREAD

**Issue by CasperWA** [BIG-MAP/BattINFO#12]
This issue represents the development of the ontology pertaining to the **electrode**.
It will be developed in the separate Turtle ontology file `electrode.ttl`.

**Involved**: @CasperWA, @eibfl-dtu, Rosa, @MiranGaberscek, Inga

**Comments**:
Positive Electrode ~= Negative Electrode.
Electrodes are general, difference is operating at a given potential.
Use the relative electrochemical potentials of the of the electrodes to distinguish positive from negative.

**Comment by jesper-friis** [comment]
@CasperWA, I expect it is fine to close this issue.

**Comment by CasperWA** [comment]
> @CasperWA, I expect it is fine to close this issue.

Yes. I'd consider this fine, as the issue is stale and development has moved past the need for it.
