### ISSUE TITLE
Non-resolving URL in 0.8.0-beta/battery: import from https://raw.githubusercontent.com/BIG-MAP/BattINFO/master/battinfo.ttl

### ISSUE THREAD

**Issue by deepananbu** [BIG-MAP/BattINFO#156]
Hi everybody,

we are using an version of battInfo at TIB Terminology service from https://raw.githubusercontent.com/BIG-MAP/BattINFO/master/battinfo.ttl

This document imports a 0.8.0-beta/battery : https://w3id.org/emmo/domain/battery/0.8.0-beta/battery. This URL is not working any longer and giving (404). 

Could you please check?

Thanks,
Deepan A

**Comment by jsimonclark** [comment]
Hi Deepan, 

thank you for highlighting this issue. We are working on a fix and will push it over the weekend.

**Comment by jsimonclark** [comment]
The URL should now reserve to the turtle file. You can also get the latest version at: [https://w3id.org/emmo/domain/battery/0.10.0-beta/battery](https://w3id.org/emmo/domain/battery/0.10.0-beta/battery). We are preparing the 1.0.0 release to coincide with the release of EMMO 1.0.0
