### ISSUE TITLE
Separate namespace for electrochemistry.ttl

### ISSUE THREAD

**Issue by jesper-friis** [BIG-MAP/BattINFO#38]
Since electrochemistry.ttl contains generic electrochemical concepts that are also relevant for corrosion and other electrochemical fields, to eventually factor it out into an separate domain ontology. It should then have its own namespace. To prepare for that, we could already now introduce the namespace `http://emmo.info/electrochemistry`.

**Comment by francescalb** [comment]
I agree with this one.
