### ISSUE TITLE
Structuring electrode

### ISSUE THREAD

**Issue by jesper-friis** [BIG-MAP/BattINFO#46]
Nothing can be both an electrode and cathode at the same time, so I think we should make Electrode and Cathode disjoint.

Would it also be possible to find a good common name for the class of all the subclasses of Electrode who's name ends with "Electrode"? A real world electrode would be both an individual of this class and as well as either Electrode or Cathode. 

Shouldn't the elucidation of Electrode and Cathode also state the direction of the net electron flow?

**Comment by francescalb** [comment]
Do you mean that nothing can be Anode and Cathode at the same time?

**Comment by jesper-friis** [comment]
You are right Francesca. It should be "nothing can be Anode and Cathode at the same time"

**Comment by jsimonclark** [comment]
Yes, I disjointed Anode and Cathode as well as WorkingElectrode and CounterElectrode. The standard definition for Anode and Cathode is linked to if the reaction is an oxidation or reduction. We can add net electron flow as a comment.
