### ISSUE TITLE
Import statements are not resolved properly

### ISSUE THREAD

**Issue by fengel** [BIG-MAP/BattINFO#56]
I can't open https://raw.githubusercontent.com/BIG-MAP/BattINFO/master/battinfo.ttl properly in Protege (no classes are available). 
As far as I can see, the reason is that the  import cannot be resolved, because the ontologies "model" and "observation" are not avilable.

owl:imports <http://emmo.info/BattINFO/0.1.0/models> ,
                    <http://emmo.info/BattINFO/0.1.0/observations>

**Comment by francescalb** [comment]
I am sorry for the late reply on this issue. The current master branch should work. We are working towards a release beginning next year and this can be followed in the 'dev' branch. 

As I believe this issue is solved, I will close it now. Please make a new one if the problem persists.
