### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by CasperWA** [BIG-MAP/BattINFO#80]
Versioning ontologies during development can be difficult.

One should use semantic versioning ([specification](https://semver.org)).
When making it clear it's a development version, one can then up the major, minor or patch version and add something like `-dev`.

However, this is not viable for the simple reason that the actual next version may differ from the used new version.

I will suggest an alternative to this: A combination between semantic versioning and calendar versioning ([specification](https://calver.org)).
This could be in the form: `MAJOR.MINOR.PATCH-YYYY.MM.DD.X` or similar, where `MAJOR`, `MINOR`, and `PATCH` refers to the semantic version, i.e., the latest properly released version.
`YYYY`, `MM`, and `DD` refers to the date of the developer release, and `X` refers to the release number on that day. One could leave out `X` if it's the first release of the day and later add it (setting it to `1`) if another release is published on the same day for the same semantic version.

The meaning of the version number is then the following for end-users: The semantic version reflects actual semantic content changes or fixes, while the calendar version reflects newer perspectives or patch updates of the original/first release of the affiliated semantic version.

To hammer through the "patch" update part one could remove the semantic `PATCH` and instead use calendar versioning for that part.
Another interpretation of the version number could be: The semantic version reflects the latest proper release version, while the calendar version reflects a (development) update to this release version. If done properly, the end-users should always refer to _only_ semantic versions of the ontology (i.e., where the calendar version is all `0`, e.g., `1.3.2-0000.00.00` aka. `1.3.2`).

**Comment by jsimonclark** [comment]
You are right that this is both important and difficult. It's something that we need to dedicate more attention to, especially now that we are converging on stable releases across the EMMO universe. Personally, I think using a combination of semantic and calendar versioning would be more confusing than helpful. But one way or the other, we should use the same [versioning system across all of EMMO](https://github.com/emmo-repo/EMMO/blob/master/doc/EMMO_governance.md#releases-and-versioning). For that reason, I recommend moving this topic to the [EMMO](https://github.com/emmo-repo/EMMO).
