### ISSUE TITLE
ontopy not python3 compatible

### ISSUE THREAD

**Issue by helgestein** [BIG-MAP/BattINFO#90]
When trying out the example given in the readme you get an error because ontopy is 13 years old and not updated to python3 includign the dependecies like old sparkql.
Potentially it might also be great to move BattInfo to another format than ttl

**Comment by helgestein** [comment]
So what works is rdflib
`python
from rdflib import Graph
graph = Graph()
graph.parse('https://raw.githubusercontent.com/BIG-MAP/BattINFO/master/battery.ttl', format='ttl')
`

**Comment by helgestein** [comment]
Maybe it's best if I explain what I want: I want to mix OWL and python using owlready2

**Comment by francescalb** [comment]
Hi,  you are probably installing the wrong package.
This ontopy is a part of the package emmontopy, which you can install with  `pip install emmontopy`

https://github.com/emmo-repo/EMMOntoPy
https://emmo-repo.github.io/EMMOntoPy/0.4.0/

**Comment by francescalb** [comment]
I have updated the README to clarify which ontopy we are using in #91 . I hope this helps.

**Comment by helgestein** [comment]
yes thanks!
